"""empty message

Revision ID: 22d2eaa0b6a4
Revises: 7f3b1df180b0
Create Date: 2016-09-18 18:27:11.528496

"""

# revision identifiers, used by Alembic.
revision = '22d2eaa0b6a4'
down_revision = '7f3b1df180b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('category', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'category')
    ### end Alembic commands ###
