"""empty message

Revision ID: 2b239789c407
Revises: 370e5c8f280d
Create Date: 2016-08-16 15:27:48.742322

"""

# revision identifiers, used by Alembic.
revision = '2b239789c407'
down_revision = '370e5c8f280d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('uri', sa.String(length=220), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'uri')
    ### end Alembic commands ###
