"""empty message

Revision ID: 2cab3229615f
Revises: 8399a6b1072f
Create Date: 2016-09-18 13:59:34.425924

"""

# revision identifiers, used by Alembic.
revision = '2cab3229615f'
down_revision = '8399a6b1072f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('exec_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer_job', 'exec_time')
    ### end Alembic commands ###
