"""empty message

Revision ID: 2cc11f9fdbd5
Revises: d5085f4caba8
Create Date: 2016-09-18 15:01:51.950067

"""

# revision identifiers, used by Alembic.
revision = '2cc11f9fdbd5'
down_revision = 'd5085f4caba8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('commission', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer_job', 'commission')
    ### end Alembic commands ###
