"""empty message

Revision ID: 3151795d5911
Revises: 9fa5f4e041eb
Create Date: 2016-10-09 17:46:43.506218

"""

# revision identifiers, used by Alembic.
revision = '3151795d5911'
down_revision = '9fa5f4e041eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('icon', sa.String(length=200), nullable=True))
    op.add_column('printer', sa.Column('location', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'location')
    op.drop_column('printer', 'icon')
    ### end Alembic commands ###
