"""empty message

Revision ID: 51e7783f960e
Revises: bcbd631fe11b
Create Date: 2016-09-20 18:00:04.278814

"""

# revision identifiers, used by Alembic.
revision = '51e7783f960e'
down_revision = 'bcbd631fe11b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job_title', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job_title')
    ### end Alembic commands ###
