"""empty message

Revision ID: 7f3b1df180b0
Revises: 2cc11f9fdbd5
Create Date: 2016-09-18 17:18:27.035220

"""

# revision identifiers, used by Alembic.
revision = '7f3b1df180b0'
down_revision = '2cc11f9fdbd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_role')
    ### end Alembic commands ###
