"""empty message

Revision ID: 8399a6b1072f
Revises: 03798c930e68
Create Date: 2016-09-13 12:23:50.557707

"""

# revision identifiers, used by Alembic.
revision = '8399a6b1072f'
down_revision = '03798c930e68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('filename', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer_job', 'filename')
    ### end Alembic commands ###
