"""empty message

Revision ID: 9fa5f4e041eb
Revises: 51e7783f960e
Create Date: 2016-10-09 16:24:18.035431

"""

# revision identifiers, used by Alembic.
revision = '9fa5f4e041eb'
down_revision = '51e7783f960e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('uuid', sa.String(length=150), nullable=True))
    op.drop_constraint(u'printer_uri_key', 'printer', type_='unique')
    op.create_unique_constraint(None, 'printer', ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printer', type_='unique')
    op.create_unique_constraint(u'printer_uri_key', 'printer', ['uri'])
    op.drop_column('printer', 'uuid')
    ### end Alembic commands ###
