"""empty message

Revision ID: bc59f1246e2d
Revises: c88083f20273
Create Date: 2016-09-02 12:50:39.605852

"""

# revision identifiers, used by Alembic.
revision = 'bc59f1246e2d'
down_revision = 'c88083f20273'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('paper_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer_job', 'paper_price')
    ### end Alembic commands ###
