"""empty message

Revision ID: bcbd631fe11b
Revises: 22d2eaa0b6a4
Create Date: 2016-09-20 11:43:10.334715

"""

# revision identifiers, used by Alembic.
revision = 'bcbd631fe11b'
down_revision = '22d2eaa0b6a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dob')
    ### end Alembic commands ###
