"""empty message

Revision ID: d5085f4caba8
Revises: 2cab3229615f
Create Date: 2016-09-18 14:20:21.482766

"""

# revision identifiers, used by Alembic.
revision = 'd5085f4caba8'
down_revision = '2cab3229615f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('page', sa.Integer(), nullable=True))
    op.drop_column('printer_job', 'page_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer_job', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('printer_job', 'page')
    ### end Alembic commands ###
